### PR TITLE
Implement basic conversions

### PR DESCRIPTION
**Pull request by avh4**
Collaborating on this PR:
  - Check the most-recent comments on this PR to see if anyone is actively working on it.  If not, continue:
  - Post a commenting stating what you are starting work on
  - Make a PR against this branch (`basic-conversions`)
  - Post a comment when you are done doing active work so others can pick up from there (including a link to your PR against this branch)

---

To include the following from the detailed discussion at #4:

- [x] `fromRgba : { red : Float, green : Float, blue : Float, alpha : Float } -> Color`
- [x] `rgb255 : Int -> Int -> Int -> Color`
- [x] `rgb : Float -> Float -> Float -> Color`
- [x] `rgba : Float -> Float -> Float -> Float -> Color`
- [x] `toRgba : Color -> { red : Float, green : Float, blue : Float, alpha : Float }`
- [x] `toHex : Color -> { hex : String, alpha : Float }`
- [x] `fromHex : String -> Color`

### CODE REVIEW

**Comment by avh4** [comment]
I'm stopping work for tonight.  Feel free to contribute following the instructions at the top of this PR.  I'll comment again when I'm picking this up again.

**Comment by 2mol** [comment]
I will now start work on the functions above that you haven't done yet, as well as some of the documentation.

**Comment by 2mol** [comment]
Ok, done for the day. I hope I'm not forgetting anything, but I should have done the following:

- completed all fromRgb functions
- clamp color channels to 0.0 - 1.0
- doc fixes and tweaks
- consolidated fromRgb functions, to make sure we're only using one implemented logic
- toHex done
- fromHsla and related functions done

https://github.com/avh4/elm-color/pull/7

I hope nothing is too bikesheddy! If anything seems that way, it's just that I'm in the habit of changing things immediately, as I come across them.

Cheers

**Comment by avh4** [comment]
I'm picking this up again, starting with merging 2mol's PR and adding tests for the conversions added there, and then finishing `fromHex`.

**Comment by avh4** [comment]
I'm moving the HSL work to a separate branch (#8), since it seems like it will be a bit of work to get the conversion accurate.

**Comment by avh4** [comment]
I'm done working on this for tonight.  Remaining work is to finish `fromHex`, (and the HSL conversions were moved to #8 )

**Comment by avh4** [comment]
I'm picking this up again to finish `fromHex`

**Comment by avh4** [comment]
Merging to `dev-1.0.0` branch -- further comments can go to #9

**Pull request merged**
